version: "3"

tasks:
  build:
    cmds:
      - odin build src -out:pvn
      - cp pvn test/busemann-diffuser/
    aliases: [b]

  test:
    cmds:
      - odin test src -define:ODIN_TEST_THREADS=1
    aliases: [t]

  test-slice:
    cmds:
      - task: build
      - ./pvn test-slice
    aliases: [s]

  test-duct:
    cmds:
      - task: build
      - ./pvn test-duct
    aliases: [d]
